function Flag_Custom() {
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.NAME,"Bonnie");
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.LV,1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.HP_MAX,15);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.HP,15);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM+1,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM+2,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM+3,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM+4,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM+5,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM+6,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM+7,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM_WEAPON,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM_ARMOR,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ATK,10);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.DEF,10);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.SPD,2);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.INV,40);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.BATTLE_MENU_FIGHT_OBJ,battle_menu_fight_knife);

	Flag_Set(FLAG_TYPE.TEMP,FLAG_TEMP.BATTLE_ROOM_RETURN,-1);
	Flag_Set(FLAG_TYPE.TEMP,FLAG_TEMP.TRIGGER_WARP_LANDMARK,noone);
	Flag_Set(FLAG_TYPE.TEMP,FLAG_TEMP.TRIGGER_WARP_DIR,-1);

	Flag_Set(FLAG_TYPE.TEMP,FLAG_TEMP.TEXT_TYPER_CHOICE,-1);
	//This code ensures that choices work in-game.
	
	Flag_Set(FLAG_TYPE.TEMP,FLAG_TEMP.INTERACTS_OBJ_LOCAL_LIST,ds_list_create());
	Flag_Set(FLAG_TYPE.TEMP,FLAG_TEMP.INTERACTS_OBJ_LOCAL_MAX,0);
	Flag_Set(FLAG_TYPE.TEMP,FLAG_TEMP.INTERACTS_OBJ_GLOBAL,0);
	Flag_Set(FLAG_TYPE.TEMP,FLAG_TEMP.INTERACTS_OBJ_GLOBAL_MAX,0);
	Flag_Set(FLAG_TYPE.TEMP,FLAG_TEMP.INTERACTS_NPC_LOCAL_LIST,ds_list_create());
	Flag_Set(FLAG_TYPE.TEMP,FLAG_TEMP.INTERACTS_NPC_LOCAL_MAX,0);
	Flag_Set(FLAG_TYPE.TEMP,FLAG_TEMP.INTERACTS_NPC_GLOBAL,0);
	Flag_Set(FLAG_TYPE.TEMP,FLAG_TEMP.INTERACTS_NPC_GLOBAL_MAX,0);
	Flag_Set(FLAG_TYPE.TEMP,FLAG_TEMP.CALLS_LOCAL_LIST,0);
	Flag_Set(FLAG_TYPE.TEMP,FLAG_TEMP.CALLS_GLOBAL,0);
	Item_SetWeapon(item_stick);
	Item_SetArmor(item_bandage);
	Item_Add(item_tml);


}
