draw_set_valign(fa_bottom)
draw_set_halign(fa_center)
draw_set_font(font_crypt_of_tomorrow)
draw_set_color(c_dkgray)
draw_text_transformed(320,478,"(THIS IS A PLACEHOLDER)",2,2,0)
draw_set_valign(fa_middle)
draw_set_color(c_white)
draw_set_font(determination_mono)
draw_set_color(c_white)
draw_text_transformed(320,240,text,2,2,0)
draw_set_halign(fa_left)
draw_set_valign(fa_top)