depth=DEPTH_BATTLE.ENEMY;
_enemy_slot=-1;
image_speed=0;
image_index=0;
_damage_timer=-1;
enemy_ailments=-1;
enemy_ailment_numbers=-1;
arm_index[0]=0;
arm_index[1]=0;
arm_rot=0;
_did_special=0;
fx_mode=0;
_fx_timer=0;
//Flag_Set(FLAG_TYPE.TEMP,FLAG_TEMP.ENEMY_AP,10)
//Flag_Set(FLAG_TYPE.TEMP,FLAG_TEMP.ENEMY_SP,12)
battle_ui.display_enemy_ap=Flag_Get(FLAG_TYPE.TEMP,FLAG_TEMP.ENEMY_AP,0);
new_color=c_white
color_timer=0;