var STATE=Battle_GetState();
var MENU=Battle_GetMenu();
if(STATE==BATTLE_STATE.MENU && MENU!=BATTLE_MENU.BUTTON && MENU!=BATTLE_MENU.SKILL_EVENT && MENU!=BATTLE_MENU.SKILL_DAMAGE && MENU!=BATTLE_MENU.SKILL_EVENT_END){
	draw_self();
}