function Macro_Flag() {
	enum FLAG_TYPE{
		STATIC,
		DYNAMIC,
		TEMP,
		INFO,
		SETTINGS,
		DEMO
	};

#region static
	enum FLAG_STATIC{
		NAME,
		LV,
		HP_MAX,
		HP,
		AP_MAX,
		AP,
		SP_MAX,
		SP,
		ATK,
		ATK_ITEM,
		DEF,
		DEF_ITEM,
		SPD,
		SPD_ITEM,
		INV,
		INV_ITEM,
		EXP,
		GOLD,
		ITEM,
		ITEM_END=FLAG_STATIC.ITEM+8-1,
		ITEM_WEAPON,
		ITEM_ARMOR,
		PHONE,
		PHONE_END=FLAG_STATIC.PHONE+8-1,
		BATTLE_MENU_FIGHT_OBJ,
		PLOT,
		MURDUR_LV,
		KILLS,
		ROOM,
		TIME,
		BOX,
		BOX_END=FLAG_STATIC.BOX+20-1,
		PARTY_NAME,
		PARTY_NAME_END=FLAG_STATIC.PARTY_NAME+4-1,
		PARTY_HP,
		PARTY_HP_END=FLAG_STATIC.PARTY_HP+4-1,
		PARTY_HP_MAX,
		PARTY_HP_MAX_END=FLAG_STATIC.PARTY_HP_MAX+4-1,
		PARTY_MOVESETS,
		PARTY_MOVESETS_END=FLAG_STATIC.PARTY_MOVESETS+4-1,
		PARTY_SPECIAL,
		PARTY_SPECIAL_END=FLAG_STATIC.PARTY_SPECIAL+4-1,
		PARTY_PASSIVE,
		PARTY_PASSIVE_END=FLAG_STATIC.PARTY_PASSIVE+4-1,
		PARTY_AILMENTS,
		PARTY_AILMENTS_END=FLAG_STATIC.PARTY_AILMENTS+4-1,
		PARTY_AILMENTS_NUMBERS,
		PARTY_AILMENTS_NUMBERS_END=FLAG_STATIC.PARTY_AILMENTS+4-1,
	};
#endregion

#region dynamic
	enum FLAG_DYNAMIC{
	};
#endregion

#region temp
	enum FLAG_TEMP{
		FUN,
		SAVE_SLOT,
		ENCOUNTER,
		BATTLE_ROOM_RETURN,
		GAMEOVER_SOUL_X,
		GAMEOVER_SOUL_Y,
		TRIGGER_WARP_LANDMARK,
		TRIGGER_WARP_DIR,
		TEXT_TYPER_CHOICE,
		FRAME_SKIP,
		INTERACTS_OBJ_LOCAL_LIST,
		INTERACTS_OBJ_LOCAL_MAX,
		INTERACTS_OBJ_GLOBAL,
		INTERACTS_OBJ_GLOBAL_MAX,
		INTERACTS_NPC_LOCAL_LIST,
		INTERACTS_NPC_LOCAL_MAX,
		INTERACTS_NPC_GLOBAL,
		INTERACTS_NPC_GLOBAL_MAX,
		CALLS_LOCAL_LIST,
		CALLS_GLOBAL,
		CALLS_GLOBAL_MAX,
		MEMBER_ACTIVE,
		MEMBER_AILMENTS,
		MEMBER_AILMENTS_END=FLAG_TEMP.MEMBER_AILMENTS+2-1,
		MEMBER_TEMP_ITEM,
		MEMBER_TEMP_ITEM_END=FLAG_TEMP.MEMBER_TEMP_ITEM+8-1,
		GOSPEL_PASSIVE_BOOST,
		WHIMSIE_BOMB_FUSE,
		ENEMY_AP_MAX,
		ENEMY_SP_MAX,
		ENEMY_AP,
		ENEMY_SP,
		PARTY_BLOCK,
		PARTY_BLOCK_END=FLAG_TEMP.PARTY_BLOCK+4-1,
	};
#endregion

#region info
	enum FLAG_INFO{
		NAME,
		LV,
		TIME,
		ROOM
	};
#endregion

#region settings
	enum FLAG_SETTINGS{
		LANGUAGE,
		GAMEPAD_CONFIRM,
		GAMEPAD_CANCEL,
		GAMEPAD_MENU
	};
#endregion

#region demo
	enum FLAG_DEMO{
		DATA
	};
#endregion


}
