function Macro_Battle() {
	enum BATTLE_STATE{
		MENU,
		DIALOG,
		ATTACK_PREPARATION,
		ATTACK_PHASE,
		SECOND_ATTACK_PHASE,
		ATTACK_RESETTING,
		RESULT,
		SKILL_EVENT_TRIGGER,
		AILMENT_EFFECTS,
		AILMENT_DAMAGE,
		AILMENT_EFFECTS_AFTER,
	};

	enum BATTLE_MENU{
		BUTTON,
		SKILL_SELECT,
		SKILL_TARGET,
		SKILL_EVENT,
		SKILL_DAMAGE,
		SKILL_DAMAGE_EXTRA,
		SKILL_EVENT_END,
		SKILL_POWER,
		SKILL_FUSE,
		CHECK_TARGET,
		CHECK_DESCRIPTION,
		BAG,
		BAG_EVENT,
		DEFEND,
		SPECIAL
	};

	enum BATTLE_MENU_CHOICE_BUTTON{
		SKILL,
		CHECK,
		BAG,
		DEFEND,
		SPECIAL
	};

	enum BATTLE_MENU_CHOICE_MERCY{
		SPARE,
		FLEE
	};

	enum BATTLE_ENEMY_EVENT{
		INIT,
		BATTLE_START,
		MENU_START,
		MENU_SWITCH,
		MENU_CHOICE_SWITCH,
		MENU_END,
		DIALOG_START,
		DIALOG_END,
		ATTACK_PREPARATION_START,
		ATTACK_PREPARATION_END,
		TURN_START,
		TURN_END,
		ATTACK_RESETTING_START,
		ATTACK_RESETTING_END
	};

	enum BATTLE_SOUL_EVENT{
		BULLET_COLLISION,
		HURT
	};

	enum BATTLE_BULLET_EVENT{
		SOUL_COLLISION,
		TURN_END
	};

	enum BATTLE_TURN_EVENT{
		ATTACK_PREPARATION_START,
		ATTACK_PREPARATION_END,
		TURN_START,
		TURN_END
	};

	enum BATTLE_MENU_FIGHT_EVENT{
		ANIM,
		DAMAGE,
		END
	};

	enum BATTLE_BOARD{
		X=320,
		Y=320,
		UP=65,
		DOWN=65,
		LEFT=283,
		RIGHT=283
	};

	enum BATTLE_TURN{
		TIME,
		BOARD_X,
		BOARD_Y,
		BOARD_UP,
		BOARD_DOWN,
		BOARD_LEFT,
		BOARD_RIGHT,
		BOARD_MOVE_TWEEN,
		BOARD_MOVE_EASE,
		BOARD_MOVE_MODE,
		BOARD_MOVE_SPEED,
		BOARD_MOVE_DURATION,
		BOARD_SIZE_TWEEN,
		BOARD_SIZE_EASE,
		BOARD_SIZE_MODE,
		BOARD_SIZE_SPEED,
		BOARD_SIZE_DURATION,
		BOARD_RESET_X,
		BOARD_RESET_Y,
		BOARD_RESET_UP,
		BOARD_RESET_DOWN,
		BOARD_RESET_LEFT,
		BOARD_RESET_RIGHT,
		BOARD_RESET_MOVE_TWEEN,
		BOARD_RESET_MOVE_EASE,
		BOARD_RESET_MOVE_MODE,
		BOARD_RESET_MOVE_SPEED,
		BOARD_RESET_MOVE_DURATION,
		BOARD_RESET_SIZE_TWEEN,
		BOARD_RESET_SIZE_EASE,
		BOARD_RESET_SIZE_MODE,
		BOARD_RESET_SIZE_SPEED,
		BOARD_RESET_SIZE_DURATION,
		SOUL_X,
		SOUL_Y
	};

	enum BATTLE_TURN_BOARD_TRANSFORM_MODE{
		SPEED,
		DURATION
	};

	#macro RED_COLOR make_color_rgb(255,0,62)
	#macro MAROON_COLOR make_color_rgb(113,20,20)
	#macro LIME_COLOR make_color_rgb(76,255,0)
	#macro DKAQUA_COLOR make_color_rgb(00,179,231)
	#macro DEEPAQUA_COLOR make_color_rgb(00,104,128)
	#macro AQUA_COLOR make_color_rgb(0,179,231)
	#macro LTAQUA_COLOR make_color_rgb(20,251,251)
	#macro DULLAQUA_COLOR make_color_rgb(0,155,190)
	#macro GOLD_COLOR make_color_rgb(255,197,0)
	#macro DKGRAY_COLOR make_color_rgb(49,49,49)
	#macro WHIMSIE_COLOR make_color_rgb(85,203,230)
	#macro GOSPEL_COLOR make_color_rgb(104,0,229)
	#macro MOPSY_COLOR make_color_rgb(225,67,185)
	#macro TOADIE_COLOR make_color_rgb(169,169,169)
	#macro AUTORIEL_COLOR make_color_rgb(94,84,146)
}
